/* ============================================
   OCS — Main JS
   Nav · Language Switcher · Scroll Animations
   ============================================ */

/* ─── Translations ────────────────────────── */
const TRANSLATIONS = {
  en: {
    dir: 'ltr',
    nav_home: 'Home', nav_about: 'About', nav_services: 'Services',
    nav_projects: 'Projects', nav_realestate: 'Real Estate', nav_contact: 'Contact',
    realestate_coming_soon: 'Coming Soon',
    realestate_journey: 'Are you ready for your journey in Real Estate?',
    realestate_tagline_1: 'Finding a property',
    realestate_tagline_2: 'is easy.',
    realestate_tagline_3: 'Finding the right one',
    realestate_tagline_4: 'is not.',
    realestate_sub_brand: 'OCS Real Estate',
    hero_label: 'Online Construction Services',
    hero_h1: 'Building With Purpose,<br>Finishing With Precision.',
    hero_sub: 'We undertake construction and renovation projects of all scales — with quality workmanship, proper supervision, and attention to detail.',
    hero_cta1: 'View Projects', hero_cta2: 'About Us',
    hero_scroll: 'Scroll',
    stats_founded: 'Founded', stats_projects: 'Projects Completed',
    stats_team: 'Specialists on Team', stats_years: 'Years of Experience',
    slider_label: 'Our Work',
    slider_h2: 'Before & After',
    slider_p: 'Complete exterior renovation and landscaping — from raw construction to a finished luxury villa with pool.',
    slider_before: 'Before', slider_after: 'After',
    services_label: 'What We Do',
    services_h2: 'Our Services',
    services_p: 'From new builds to full renovations — we manage every stage with experienced engineers and specialist crews.',
    s1_title: 'New Constructions', s1_p: 'Residential & commercial buildings from foundation to final delivery.',
    s2_title: 'Renovations', s2_p: 'Complete interior renovation of apartments, houses, offices and shops.',
    s3_title: 'Engineering & Technical', s3_p: 'Permits, studies, architectural drawings and full project consulting.',
    s4_title: 'Exterior & Energy', s4_p: 'Thermal insulation, facade works, waterproofing and roof repairs.',
    s5_title: 'Project Supervision', s5_p: 'Continuous on-site coordination and quality control throughout every project.',
    learn_more: 'Learn More',
    projects_label: 'Portfolio',
    projects_h2: 'Projects',
    projects_p: 'A selection of completed works across residential renovations, exterior restorations and new constructions.',
    view_all: 'View All Projects',
    cta_h2: 'Ready to Start Your Project?',
    cta_p: 'Get in touch with our team for a consultation and project estimate.',
    cta_btn: 'Contact Us',
    footer_tagline: 'Premium construction and renovation services — built on quality, delivered with precision.',
    footer_nav: 'Navigation', footer_services: 'Services', footer_contact_title: 'Contact',
    footer_legal: 'Legal',
    cookie_link: 'Cookie & Privacy Policy',
    footer_copy: '© 2024 Online Construction Services (OCS). All rights reserved.',
    pm_label: 'Project Manager',
    about_hero_p: 'Founded in 2024. Built on decades of combined engineering and construction experience.',
    about_story_label: 'Our Story', about_who_h2: 'Who We Are',
    about_p1: 'Online Construction Services (OCS) was founded in 2024 following the increasing demand and growth of construction projects undertaken through our long-standing technical company.',
    about_p2: 'With years of experience in the construction and engineering sector, the creation of a dedicated construction company was a necessary step in order to achieve better project coordination, direct supervision, and more efficient management of ongoing works.',
    about_p3: 'Coming from a strong technical background, our company works closely with a team of experienced engineers and technical professionals, including civil engineers, architects, surveyors, mechanical and electrical engineers, along with specialized construction crews.',
    about_p4: 'We undertake projects covering all aspects of construction, including new residential buildings, renovations, restorations, commercial projects, energy upgrades, and complete turn-key solutions.',
    about_phil_label: 'Our Philosophy',
    about_phil_h2: '"Every Project Deserves Professionalism, Responsibility, and Respect."',
    about_phil_p: 'Our approach is based on proper planning, quality workmanship, attention to detail, and continuous communication with the client throughout every stage of the project. Our goal is to deliver projects that combine functionality, durability, and high construction standards while building long-term relationships based on trust and consistency.',
    about_drives_label: 'What Drives Us', about_approach_h2: 'Our Approach',
    about_app_p1: 'At Online Construction Services (OCS), we believe that every project should be treated with professionalism, responsibility, and respect for both the client\'s vision and the technical requirements of the work.',
    about_app_p2: 'Our goal is to deliver projects that combine functionality, durability, and high construction standards while building long-term relationships based on trust and consistency.',
    about_app_p3: 'From small-scale renovations to demanding construction projects, we approach every work with the same level of professionalism, supervision, and responsibility.',
    view_services: 'View Our Services',
    about_team_label: 'Our Team', about_team_h2: 'Specialists & Experts',
    about_team_p: 'We collaborate with a multidisciplinary team of licensed professionals and skilled tradespeople.',
    team_civil_h4: 'Civil Engineers', team_civil_p: 'Structural design, reinforced concrete, and construction oversight.',
    team_arch_h4: 'Architects', team_arch_p: 'Architectural drawings, permits, and space planning solutions.',
    team_survey_h4: 'Surveyors', team_survey_p: 'Topographic surveys, boundary measurements, and site analysis.',
    team_mep_h4: 'MEP Engineers', team_mep_p: 'Mechanical, electrical, and plumbing systems design and installation.',
    team_crew_h4: 'Construction Crews', team_crew_p: 'Specialized tradespeople in masonry, plastering, tiling, and finishing.',
    srv_page_label: 'What We Do', srv_page_h1: 'Our Services',
    srv_page_p: 'Online Construction Services (OCS) undertakes construction and technical projects of all scales, providing reliable solutions with emphasis on proper execution, supervision, and construction quality.',
    srv1_label: 'Construction', srv1_p: 'We undertake the construction of residential and commercial buildings, from the initial stage of the project up to final delivery.',
    srv1_li1: 'Reinforced concrete works', srv1_li2: 'Masonry and plastering', srv1_li3: 'Structural construction works',
    srv1_li4: 'Turn-key residential projects', srv1_li5: 'Site supervision and coordination', srv1_li6: 'General construction works',
    srv2_label: 'Renovation', srv2_p: 'Complete renovation works for apartments, houses, offices, shops, and commercial spaces. Every renovation project is approached according to the needs and functionality of the space.',
    srv2_li1: 'Interior remodeling', srv2_li2: 'Kitchen and bathroom renovations', srv2_li3: 'Flooring and tiling works',
    srv2_li4: 'Ceiling and drywall constructions', srv2_li5: 'Painting works', srv2_li6: 'Space reconfiguration',
    srv3_label: 'Technical', srv3_p: 'In cooperation with our technical company and engineering team, we provide full technical support and project guidance.',
    srv3_li1: 'Building permits', srv3_li2: 'Engineering studies', srv3_li3: 'Architectural drawings',
    srv3_li4: 'Topographic surveys', srv3_li5: 'Technical inspections', srv3_li6: 'Project supervision and consulting',
    srv4_label: 'Exterior', srv4_p: 'We undertake exterior renovation and restoration works aimed at improving both the appearance and energy performance of buildings.',
    srv4_li1: 'Thermal insulation systems', srv4_li2: 'Facade repairs and painting', srv4_li3: 'Waterproofing works',
    srv4_li4: 'Roof repairs and insulation', srv4_li5: 'Balcony restorations', srv4_li6: 'Exterior maintenance works',
    srv5_label: 'Management', srv5_p: 'Every project is monitored with continuous supervision and coordination in order to ensure proper execution and timely completion.',
    srv5_li1: 'Construction quality control', srv5_li2: 'Worksite organization', srv5_li3: 'Coordination of crews and suppliers',
    srv5_li4: 'Compliance with project specifications', srv5_li5: 'Time schedule management', srv5_li6: 'Direct communication with the client',
    proj_page_label: 'Portfolio', proj_page_h1: 'Projects',
    proj_page_p: 'At Online Construction Services (OCS), every project reflects our commitment to quality construction, proper planning, and attention to detail. Our portfolio includes residential developments, renovations, commercial projects, exterior restorations, and technical works.',
    filter_all: 'All', filter_renovation: 'Renovation', filter_construction: 'Construction', filter_exterior: 'Exterior', filter_interior: 'Interior',
    proj_more_soon: 'More projects coming soon — portfolio is continuously updated.',
    contact_hero_p: 'Contact us to discuss your project. We will be happy to help.',
    contact_lets_talk: 'Let\'s Talk',
    contact_sub: 'We are available for any question regarding construction and renovations.',
    contact_phone_lbl: 'Phone', contact_area_lbl: 'Area', contact_area_val: 'Chalkida, Evia',
    contact_form_title: 'Send us a Message',
    contact_form_p: 'Fill in the form and we will get back to you as soon as possible.',
    contact_name_lbl: 'Full Name *', contact_phone_field: 'Phone', contact_email_lbl: 'Email *',
    contact_service_lbl: 'Service', contact_msg_lbl: 'Message *',
    contact_required: '* Required fields', contact_submit_btn: 'Send Message',
    contact_service_placeholder: '— Select a service —', contact_other: 'Other',
    contact_success_msg: '✓ Your message was sent successfully! We will contact you shortly.',
    // --- Extended translations ---
    proj_info_category: 'Category',
    proj_info_type: 'Type',
    proj_info_scope: 'Scope',
    proj_info_status: 'Status',
    proj_info_year: 'Year',
    proj_status_completed: 'Completed',
    project_gallery_title: 'Project Gallery',
    project_overview_title: 'Project Overview',
    project_about_title: 'About This Project',
    project_back_all: 'Back to All Projects',
    project_more_works: 'More Projects',
    project_related_title: 'Related Works',
    proj_rail_kick: 'OCS Portfolio',
    proj_intro_p1: 'At Online Construction Services (OCS), every project reflects our commitment to quality construction, proper planning, and attention to detail.',
    proj_intro_p2: 'Our portfolio includes residential developments, renovations, commercial projects, exterior restorations, and technical works completed through the combined experience of our construction and engineering teams.',
    proj_intro_p3: 'From small-scale renovations to demanding construction projects, we approach every project with the same level of professionalism, supervision, and responsibility.',
    proj_intro_p4: 'Below you can find a selection of projects that represent our work and construction approach across different sectors and project types.',
    cat_interior_exterior: 'Interior & Exterior Renovation',
    cat_residential_construction: 'Residential Construction',
    cat_interior_joinery: 'Interior Design & Joinery',
    cat_exterior_landscaping: 'Exterior & Landscaping',
    villa_title: 'Sea View Villa Renovation – Faros, Avlida',
    villa_desc: 'A complete exterior renovation of a sea-view villa in Faros, Avlida. The project included façade restoration, premium exterior finishes, and the construction of a modern swimming pool, delivering a refined outdoor living experience.',
    villa_scope: 'Exterior Renovation & Pool Construction',
    villa_work_1: 'Facade renovation & painting',
    villa_work_2: 'Pool construction & finishing',
    villa_work_3: 'Glass fence installation',
    villa_work_4: 'Exterior paving & landscaping',
    villa_work_5: 'Exterior lighting',
    villa_work_6: 'Shutter & window installation',
    villa_overview_p1: 'This project involved the complete exterior renovation of a two-storey sea-view villa in Faros, Avlida. The scope of work covered structural and facade restoration, premium exterior finishing, pool construction, and site landscaping.',
    villa_overview_p2: 'The finished result showcases a high-end architectural transformation — featuring restored modern facades, a custom swimming pool with premium finishing, and refined outdoor spaces designed for optimal living.',
    villa_overview_p3: 'Managed entirely by the OCS engineering team, the project was executed on schedule and in full compliance with the highest standards of safety and craftsmanship.',
    house1_title: 'Alykes Sea View Renovation',
    house1_desc: 'An extensive interior and exterior renovation of a sea-view residence in Alykes, Chalkida. The project combines modern design, high-quality craftsmanship, and functional upgrades, and is currently progressing toward completion.',
    house1_scope: 'Interior & Exterior Renovation',
    house1_overview_p1: 'This project involves a comprehensive interior and exterior renovation of a sea-view residence in Alykes, Chalkida, currently at 70% completion. The scope includes structural adjustments, scaffolding, plastering, and the installation of modern electrical and lighting systems.',
    house1_overview_p2: 'The design combines modern architectural layouts, a custom kitchen, and open-plan living spaces crafted with high-quality materials to maximize both functionality and aesthetic value.',
    house1_overview_p3: 'All construction and finishing works are managed and supervised by the OCS engineering team, ensuring high-quality standards and precision at every phase.',
    house1_status: 'Under Construction (70%)',
    house1_work_1: 'Exterior structural work & scaffolding',
    house1_work_2: 'Interior layout reconfiguration',
    house1_work_3: 'Full plastering & painting',
    house1_work_4: 'Custom kitchen installation',
    house1_work_5: 'Flooring & tiling',
    house1_work_6: 'Electrical & lighting installation',
    house2_title: 'Loukisia Sea View Residence',
    house2_desc: 'A modern sea-view residence currently under construction in Loukisia, Greece. Designed with contemporary architecture, the project combines energy efficiency, structural durability, and premium construction standards.',
    house2_scope: 'New Residential Construction',
    house2_overview_p1: 'This project involves the construction of a new modern residential villa in Loukisia, Greece, currently at 65% completion. The scope of work covers structural framework construction, brickwork, plastering, and general building installation works.',
    house2_overview_p2: 'Designed with contemporary architectural lines, the house combines energy-efficient solutions, structural durability, and premium construction standards.',
    house2_overview_p3: 'Our engineering team supervises the entire building process, coordinating specialized crews and performing regular quality checks at every stage of construction.',
    house2_status: 'Under Construction (65%)',
    house2_work_1: 'Reinforced concrete structural frame',
    house2_work_2: 'Masonry & brickwork construction',
    house2_work_3: 'External thermal insulation system',
    house2_work_4: 'Electrical & plumbing installations',
    house2_work_5: 'Premium tiling and flooring',
    house2_work_6: 'Interior & exterior painting',
    house3_title: 'Sea View Villa Renovation – Skorponeria',
    house3_desc: 'A sea-view villa renovation in Skorponeria, featuring a complete exterior transformation and the construction of a custom infinity pool. The project blends contemporary design, premium craftsmanship, and seamless outdoor living.',
    house3_scope: 'Exterior Renovation & Infinity Pool Construction',
    house3_overview_p1: 'This project involves a comprehensive exterior renovation and custom infinity pool construction for a sea-view villa in Skorponeria, currently at 90% completion. The scope includes facade restoration, high-end thermal insulation, pool structure excavation, and concrete pouring.',
    house3_overview_p2: 'The layout is optimized for an integrated indoor-outdoor living experience, featuring custom tiling, modern waterproofing systems, glass barriers, and energy-efficient pool filtration systems.',
    house3_overview_p3: 'All design, structural, and finishing works are managed and supervised by the OCS engineering team, ensuring compliance with strict building codes and premium aesthetics.',
    house3_status: 'Under Construction (90%)',
    house3_work_1: 'Excavation & site preparation',
    house3_work_2: 'Infinity pool structural framework',
    house3_work_3: 'Facade restoration & insulation',
    house3_work_4: 'Waterproofing & tiling',
    house3_work_5: 'Smart lighting & pool filtration systems',
    house3_work_6: 'Decking & outdoor landscaping',
    cookie_title: 'Cookie & Privacy Policy',
    cookie_updated: 'Last updated: January 2024',
    cookie_h1: '1. Introduction',
    cookie_p1: 'Online Construction Services (OCS) ("we", "our", or "us") is committed to protecting your personal data and respecting your privacy. This Cookie and Privacy Policy explains how we collect, use, and protect any information you provide when you visit our website.',
    cookie_h2: '2. Data Controller',
    cookie_p2: 'The data controller responsible for your personal data is Online Construction Services (OCS).',
    cookie_contact: 'Contact:',
    cookie_phone: 'Phone:',
    cookie_h3: '3. What Data We Collect',
    cookie_p3: 'We may collect the following types of data:',
    cookie_li3_1: 'Contact information — name, email address, and phone number if you contact us directly.',
    cookie_li3_2: 'Usage data — information about how you interact with our website (pages visited, time spent, browser type).',
    cookie_li3_3: 'Technical data — IP address, browser type and version, time zone, operating system.',
    cookie_h4: '4. How We Use Your Data',
    cookie_p4: 'We use the data we collect to:',
    cookie_li4_1: 'Respond to enquiries and provide project consultation.',
    cookie_li4_2: 'Improve our website and user experience.',
    cookie_li4_3: 'Comply with legal obligations.',
    cookie_p4_sub: 'We do not sell, trade, or rent your personal data to third parties.',
    cookie_h5: '5. Cookies',
    cookie_p5: 'Our website may use cookies — small text files placed on your device — to improve your browsing experience. Cookies we may use include:',
    cookie_li5_1: 'Essential cookies — necessary for the website to function correctly (e.g. language preference).',
    cookie_li5_2: 'Analytics cookies — help us understand how visitors interact with the site (e.g. Google Analytics, if enabled).',
    cookie_p5_sub: 'You can control and manage cookies through your browser settings. Note that disabling certain cookies may affect the functionality of the site.',
    cookie_h6: '6. Language Preference',
    cookie_p6: 'This website stores your selected language preference in your browser\'s localStorage. This data is not transmitted to any server and remains only on your device.',
    cookie_h7: '7. Your Rights (GDPR)',
    cookie_p7: 'Under the General Data Protection Regulation (GDPR), you have the right to:',
    cookie_li7_1: 'Access the personal data we hold about you.',
    cookie_li7_2: 'Request correction of inaccurate data.',
    cookie_li7_3: 'Request deletion of your data ("right to be forgotten").',
    cookie_li7_4: 'Object to or restrict how we process your data.',
    cookie_li7_5: 'Data portability — receive your data in a structured, machine-readable format.',
    cookie_li7_6: 'Lodge a complaint with a supervisory authority.',
    cookie_p7_sub: 'To exercise any of these rights, please contact us at:',
    cookie_h8: '8. Data Retention',
    cookie_p8: 'We retain personal data only for as long as is necessary for the purposes outlined in this policy, or as required by applicable law.',
    cookie_h9: '9. Third-Party Links',
    cookie_p9: 'Our website may contain links to third-party websites. We are not responsible for the privacy practices or content of those sites and encourage you to review their privacy policies.',
    cookie_h10: '10. Changes to This Policy',
    cookie_p10: 'We may update this Cookie and Privacy Policy from time to time. Any changes will be published on this page with an updated revision date. We encourage you to review this page periodically.',
    cookie_h11: '11. Contact',
    cookie_p11: 'If you have any questions about this policy or how we handle your data, please contact:',
    cookie_pm: 'Eteoklis Stasinopoulos — Project Manager',
    type_villa: 'Residential Villa',
    type_house: 'Residential House',
    type_residence: 'Sea View Residence',

  },
  el: {
    dir: 'ltr',
    nav_home: 'Αρχική', nav_about: 'Σχετικά', nav_services: 'Υπηρεσίες',
    nav_projects: 'Έργα', nav_realestate: 'Ακίνητα', nav_contact: 'Επικοινωνία',
    realestate_coming_soon: 'Έρχεται Σύντομα',
    realestate_journey: 'Είστε έτοιμοι για το ταξίδι σας στα ακίνητα;',
    realestate_tagline_1: 'Η εύρεση ακινήτου',
    realestate_tagline_2: 'είναι εύκολη.',
    realestate_tagline_3: 'Η εύρεση του κατάλληλου',
    realestate_tagline_4: 'όχι.',
    realestate_sub_brand: 'OCS Real Estate',
    hero_label: 'Online Construction Services',
    hero_h1: 'Δημιουργούμε με Όραμα,<br>Παραδίδουμε με Ακρίβεια.',
    hero_sub: 'Αναλαμβάνουμε κατασκευαστικά και ανακαινιστικά έργα κάθε κλίμακας — με ποιοτική εκτέλεση, σωστή εποπτεία και προσοχή στη λεπτομέρεια.',
    hero_cta1: 'Δείτε τα Έργα', hero_cta2: 'Σχετικά με Εμάς',
    hero_scroll: 'Κύλιση',
    stats_founded: 'Ίδρυση', stats_projects: 'Ολοκληρωμένα Έργα',
    stats_team: 'Ειδικοί στην Ομάδα', stats_years: 'Χρόνια Εμπειρίας',
    slider_label: 'Η Δουλειά Μας',
    slider_h2: 'Πριν & Μετά',
    slider_p: 'Πλήρης εξωτερική ανακαίνιση — από ακατέργαστη κατασκευή σε πολυτελή βίλα με πισίνα.',
    slider_before: 'Πριν', slider_after: 'Μετά',
    services_label: 'Τι Κάνουμε',
    services_h2: 'Υπηρεσίες',
    services_p: 'Από νέες κατασκευές έως ολοκληρωμένες ανακαινίσεις — διαχειριζόμαστε κάθε στάδιο με έμπειρους μηχανικούς.',
    s1_title: 'Νέες Κατασκευές', s1_p: 'Οικιστικά & εμπορικά κτίρια από τα θεμέλια έως την παράδοση.',
    s2_title: 'Ανακαινίσεις', s2_p: 'Πλήρης εσωτερική ανακαίνιση διαμερισμάτων, κατοικιών, γραφείων.',
    s3_title: 'Μηχανική & Τεχνική Υποστήριξη', s3_p: 'Άδειες, μελέτες, αρχιτεκτονικά σχέδια και τεχνική συμβουλευτική.',
    s4_title: 'Εξωτερικά & Ενεργειακά', s4_p: 'Θερμομόνωση, επενδύσεις όψεων, αδιαβροχοποίηση και επισκευές στέγης.',
    s5_title: 'Επίβλεψη Έργων', s5_p: 'Συνεχής εποπτεία και ποιοτικός έλεγχος σε κάθε φάση του έργου.',
    learn_more: 'Περισσότερα',
    projects_label: 'Χαρτοφυλάκιο',
    projects_h2: 'Έργα',
    projects_p: 'Επιλογή ολοκληρωμένων έργων σε οικιστικές ανακαινίσεις, εξωτερικές αποκαταστάσεις και νέες κατασκευές.',
    view_all: 'Όλα τα Έργα',
    cta_h2: 'Έτοιμοι να Ξεκινήσετε το Έργο σας;',
    cta_p: 'Επικοινωνήστε με την ομάδα μας για συμβουλευτική και εκτίμηση κόστους.',
    cta_btn: 'Επικοινωνία',
    footer_tagline: 'Υπηρεσίες κατασκευής και ανακαίνισης υψηλών προδιαγραφών.',
    footer_nav: 'Πλοήγηση', footer_services: 'Υπηρεσίες', footer_contact_title: 'Επικοινωνία',
    footer_legal: 'Νομικά',
    cookie_link: 'Πολιτική Cookies & Απορρήτου',
    footer_copy: '© 2024 Online Construction Services (OCS). Με επιφύλαξη παντός δικαιώματος.',
    pm_label: 'Διαχειριστής Έργων',
    about_hero_p: 'Ιδρύθηκε το 2024. Χτισμένη πάνω σε δεκαετίες εμπειρίας στη μηχανική και τις κατασκευές.',
    about_story_label: 'Η Ιστορία Μας', about_who_h2: 'Ποιοι Είμαστε',
    about_p1: 'Η Online Construction Services (OCS) ιδρύθηκε το 2024 μετά από αυξανόμενη ζήτηση και ανάπτυξη κατασκευαστικών έργων που αναλαμβάνονταν μέσω της μακροχρόνιας τεχνικής μας εταιρείας.',
    about_p2: 'Με χρόνια εμπειρίας στον κλάδο των κατασκευών και της μηχανικής, η δημιουργία αποκλειστικής κατασκευαστικής εταιρείας ήταν απαραίτητο βήμα για καλύτερο συντονισμό, άμεση εποπτεία και αποδοτικότερη διαχείριση.',
    about_p3: 'Προερχόμενοι από ισχυρό τεχνικό υπόβαθρο, συνεργαζόμαστε με ομάδα έμπειρων μηχανικών και τεχνικών, συμπεριλαμβανομένων πολιτικών μηχανικών, αρχιτεκτόνων, τοπογράφων, μηχανολόγων και ηλεκτρολόγων.',
    about_p4: 'Αναλαμβάνουμε έργα που καλύπτουν όλες τις πτυχές κατασκευής: νέα οικιστικά κτίρια, ανακαινίσεις, αποκαταστάσεις, εμπορικά έργα, ενεργειακές αναβαθμίσεις και πλήρεις λύσεις.',
    about_phil_label: 'Η Φιλοσοφία Μας',
    about_phil_h2: '"Κάθε Έργο Αξίζει Επαγγελματισμό, Υπευθυνότητα και Σεβασμό."',
    about_phil_p: 'Η προσέγγισή μας βασίζεται στον σωστό σχεδιασμό, ποιοτική εκτέλεση, προσοχή στη λεπτομέρεια και συνεχή επικοινωνία με τον πελάτη. Στόχος μας είναι έργα που συνδυάζουν λειτουργικότητα, ανθεκτικότητα και υψηλές προδιαγραφές.',
    about_drives_label: 'Τι Μας Κινεί', about_approach_h2: 'Η Προσέγγισή Μας',
    about_app_p1: 'Στην OCS πιστεύουμε ότι κάθε έργο πρέπει να αντιμετωπίζεται με επαγγελματισμό, υπευθυνότητα και σεβασμό στο όραμα του πελάτη.',
    about_app_p2: 'Ο στόχος μας είναι η παράδοση έργων που συνδυάζουν λειτουργικότητα, ανθεκτικότητα και υψηλές προδιαγραφές.',
    about_app_p3: 'Από μικρές ανακαινίσεις έως απαιτητικά κατασκευαστικά έργα, αντιμετωπίζουμε κάθε εργασία με τον ίδιο επαγγελματισμό.',
    view_services: 'Δείτε τις Υπηρεσίες Μας',
    about_team_label: 'Η Ομάδα Μας', about_team_h2: 'Ειδικοί & Εμπειρογνώμονες',
    about_team_p: 'Συνεργαζόμαστε με διεπιστημονική ομάδα αδειοδοτημένων επαγγελματιών και εξειδικευμένων τεχνιτών.',
    team_civil_h4: 'Πολιτικοί Μηχανικοί', team_civil_p: 'Στατικές μελέτες, οπλισμένο σκυρόδεμα και εποπτεία κατασκευής.',
    team_arch_h4: 'Αρχιτέκτονες', team_arch_p: 'Αρχιτεκτονικά σχέδια, άδειες και λύσεις χωροταξίας.',
    team_survey_h4: 'Τοπογράφοι', team_survey_p: 'Τοπογραφικές αποτυπώσεις, οριοθετήσεις και ανάλυση χώρου.',
    team_mep_h4: 'Μηχανολόγοι-Ηλεκτρολόγοι', team_mep_p: 'Σχεδιασμός και εγκατάσταση μηχανολογικών, ηλεκτρολογικών και υδραυλικών.',
    team_crew_h4: 'Κατασκευαστικά Συνεργεία', team_crew_p: 'Εξειδικευμένοι τεχνίτες σε τοιχοποιία, σοβαντίσματα, πλακάκια και φινίρισμα.',
    srv_page_label: 'Τι Κάνουμε', srv_page_h1: 'Υπηρεσίες',
    srv_page_p: 'Η OCS αναλαμβάνει κατασκευαστικά και τεχνικά έργα κάθε κλίμακας, με έμφαση στην ποιοτική εκτέλεση, εποπτεία και κατασκευαστική ποιότητα.',
    srv1_label: 'Κατασκευή', srv1_p: 'Αναλαμβάνουμε την κατασκευή οικιστικών και εμπορικών κτιρίων από το αρχικό στάδιο έως την τελική παράδοση.',
    srv1_li1: 'Έργα οπλισμένου σκυροδέματος', srv1_li2: 'Τοιχοποιία και σοβαντίσματα', srv1_li3: 'Κατασκευαστικά δομικά έργα',
    srv1_li4: 'Έργα κλειδί στο χέρι', srv1_li5: 'Εποπτεία και συντονισμός εργοταξίου', srv1_li6: 'Γενικές κατασκευαστικές εργασίες',
    srv2_label: 'Ανακαίνιση', srv2_p: 'Πλήρεις εργασίες ανακαίνισης για διαμερίσματα, κατοικίες, γραφεία και εμπορικούς χώρους.',
    srv2_li1: 'Εσωτερική αναδιαμόρφωση', srv2_li2: 'Ανακαίνιση κουζίνας και μπάνιου', srv2_li3: 'Εργασίες δαπέδων και πλακιδίων',
    srv2_li4: 'Οροφές και γυψοσανίδες', srv2_li5: 'Χρωματισμοί', srv2_li6: 'Αναδιαμόρφωση χώρων',
    srv3_label: 'Τεχνική Υποστήριξη', srv3_p: 'Σε συνεργασία με ομάδα μηχανικών, παρέχουμε πλήρη τεχνική υποστήριξη και καθοδήγηση έργων.',
    srv3_li1: 'Οικοδομικές άδειες', srv3_li2: 'Μηχανολογικές μελέτες', srv3_li3: 'Αρχιτεκτονικά σχέδια',
    srv3_li4: 'Τοπογραφικές αποτυπώσεις', srv3_li5: 'Τεχνικοί έλεγχοι', srv3_li6: 'Εποπτεία και συμβουλευτική έργων',
    srv4_label: 'Εξωτερικά', srv4_p: 'Αναλαμβάνουμε εξωτερικές εργασίες ανακαίνισης για βελτίωση εμφάνισης και ενεργειακής απόδοσης.',
    srv4_li1: 'Συστήματα θερμομόνωσης', srv4_li2: 'Επισκευές και χρωματισμός όψεων', srv4_li3: 'Αδιαβροχοποίηση',
    srv4_li4: 'Επισκευές στέγης και μόνωση', srv4_li5: 'Αποκατάσταση μπαλκονιών', srv4_li6: 'Γενική συντήρηση εξωτερικών',
    srv5_label: 'Διαχείριση', srv5_p: 'Κάθε έργο παρακολουθείται με συνεχή εποπτεία και συντονισμό για σωστή εκτέλεση και εγκαίρια ολοκλήρωση.',
    srv5_li1: 'Ποιοτικός έλεγχος κατασκευής', srv5_li2: 'Οργάνωση εργοταξίου', srv5_li3: 'Συντονισμός συνεργείων και προμηθευτών',
    srv5_li4: 'Τήρηση προδιαγραφών έργου', srv5_li5: 'Διαχείριση χρονοδιαγράμματος', srv5_li6: 'Άμεση επικοινωνία με τον πελάτη',
    proj_page_label: 'Χαρτοφυλάκιο', proj_page_h1: 'Έργα',
    proj_page_p: 'Στην OCS, κάθε έργο αντικατοπτρίζει τη δέσμευσή μας για ποιοτική κατασκευή, σωστό σχεδιασμό και προσοχή στη λεπτομέρεια.',
    filter_all: 'Όλα', filter_renovation: 'Ανακαίνιση', filter_construction: 'Κατασκευή', filter_exterior: 'Εξωτερικά', filter_interior: 'Εσωτερικά',
    proj_more_soon: 'Περισσότερα έργα σύντομα — το χαρτοφυλάκιο ενημερώνεται συνεχώς.',
    contact_hero_p: 'Επικοινωνήστε μαζί μας για να συζητήσουμε το έργο σας. Θα χαρούμε να σας βοηθήσουμε.',
    contact_lets_talk: 'Ας Μιλήσουμε',
    contact_sub: 'Είμαστε διαθέσιμοι για οποιαδήποτε ερώτηση σχετικά με κατασκευές και ανακαινίσεις.',
    contact_phone_lbl: 'Τηλέφωνο', contact_area_lbl: 'Περιοχή', contact_area_val: 'Χαλκίδα, Εύβοια',
    contact_form_title: 'Στείλτε μας Μήνυμα',
    contact_form_p: 'Συμπληρώστε τη φόρμα και θα επικοινωνήσουμε μαζί σας το συντομότερο.',
    contact_name_lbl: 'Ονοματεπώνυμο *', contact_phone_field: 'Τηλέφωνο', contact_email_lbl: 'Email *',
    contact_service_lbl: 'Υπηρεσία', contact_msg_lbl: 'Μήνυμα *',
    contact_required: '* Υποχρεωτικά πεδία', contact_submit_btn: 'Αποστολή Μηνύματος',
    contact_service_placeholder: '— Επιλέξτε υπηρεσία —', contact_other: 'Άλλο',
    contact_success_msg: '✓ Το μήνυμά σας στάλθηκε επιτυχώς! Θα επικοινωνήσουμε μαζί σας σύντομα.',
    // --- Extended translations ---
    proj_info_category: 'Κατηγορία',
    proj_info_type: 'Τύπος',
    proj_info_scope: 'Αντικείμενο',
    proj_info_status: 'Κατάσταση',
    proj_info_year: 'Έτος',
    proj_status_completed: 'Ολοκληρώθηκε',
    project_gallery_title: 'Γκαλερί Έργου',
    project_overview_title: 'Επισκόπηση Έργου',
    project_about_title: 'Σχετικά με το Έργο',
    project_back_all: 'Επιστροφή σε Όλα τα Έργα',
    project_more_works: 'Περισσότερα Έργα',
    project_related_title: 'Σχετικά Έργα',
    proj_rail_kick: 'Χαρτοφυλάκιο OCS',
    proj_intro_p1: 'Στην Online Construction Services (OCS), κάθε έργο αντικατοπτρίζει τη δέσμευσή μας για ποιοτική κατασκευή, σωστό σχεδιασμό και προσοχή στη λεπτομέρεια.',
    proj_intro_p2: 'Το χαρτοφυλάκιό μας περιλαμβάνει οικιστικές αναπτύξεις, ανακαινίσεις, εμπορικά έργα, εξωτερικές αποκαταστάσεις και τεχνικές εργασίες που ολοκληρώθηκαν μέσω της συνδυασμένης εμπειρίας των κατασκευαστικών και μηχανικών ομάδων μας.',
    proj_intro_p3: 'Από ανακαινίσεις μικρής κλίμακας έως απαιτητικά κατασκευαστικά έργα, προσεγγίζουμε κάθε έργο με το ίδιο επίπεδο επαγγελματισμού, επίβλεψης και υπευθυνότητας.',
    proj_intro_p4: 'Παρακάτω μπορείτε να βρείτε μια επιλογή από έργα που αντιπροσωπεύουν τη δουλειά μας και την κατασκευαστική μας προσέγγιση σε διάφορους τομείς και τύπους έργων.',
    cat_interior_exterior: 'Εσωτερική & Εξωτερική Ανακαίνιση',
    cat_residential_construction: 'Κατασκευή Κατοικίας',
    cat_interior_joinery: 'Εσωτερική Σχεδίαση & Ξυλουργικές Εργασίες',
    cat_exterior_landscaping: 'Εξωτερικοί Χώροι & Διαμόρφωση Τοπίου',
    villa_title: 'Ανακαίνιση Βίλας με Θέα Θάλασσα – Φάρος Αυλίδας',
    villa_desc: 'Πλήρης εξωτερική ανακαίνιση βίλας με θέα στη θάλασσα στον Φάρο Αυλίδας. Το έργο περιλάμβανε την ανακαίνιση των όψεων, σύγχρονα εξωτερικά φινιρίσματα και την κατασκευή νέας πισίνας, δημιουργώντας έναν κομψό και λειτουργικό υπαίθριο χώρο.',
    villa_scope: 'Εξωτερική Ανακαίνιση & Κατασκευή Πισίνας',
    villa_work_1: 'Ανακαίνιση & βάψιμο πρόσοψης',
    villa_work_2: 'Κατασκευή & φινίρισμα πισίνας',
    villa_work_3: 'Τοποθέτηση γυάλινης περίφραξης',
    villa_work_4: 'Εξωτερικές πλακοστρώσεις & διαμόρφωση κήπου',
    villa_work_5: 'Εξωτερικός φωτισμός',
    villa_work_6: 'Τοποθέτηση κουφωμάτων & ρολών',
    villa_overview_p1: 'Αυτό το έργο περιελάμβανε την πλήρη εξωτερική ανακαίνιση μιας διώροφης βίλας με θέα στη θάλασσα στον Φάρο Αυλίδας. Το πεδίο των εργασιών κάλυψε την αποκατάσταση των όψεων, σύγχρονα εξωτερικά φινιρίσματα, κατασκευή πισίνας και διαμόρφωση του περιβάλλοντος χώρου.',
    villa_overview_p2: 'Το τελικό αποτέλεσμα παρουσιάζει έναν εντυπωσιακό μετασχηματισμό — με καθαρές σύγχρονες όψεις, πισίνα υψηλών προδιαγραφών και διαμόρφωση εξωτερικών χώρων σχεδιασμένων για άνεση και λειτουργικότητα.',
    villa_overview_p3: 'Όλες οι εργασίες εκτελέστηκαν υπό τη συνεχή επίβλεψη της μηχανικής ομάδας της OCS, εξασφαλίζοντας κορυφαία ποιότητα κατασκευής και τήρηση των προδιαγραφών.',
    house1_title: 'Ανακαίνιση Κατοικίας με Θέα Θάλασσα – Αλυκές Χαλκίδας',
    house1_desc: 'Εκτεταμένη εσωτερική και εξωτερική ανακαίνιση κατοικίας με θέα στη θάλασσα στις Αλυκές Χαλκίδας. Το έργο συνδυάζει σύγχρονο σχεδιασμό, ποιοτική κατασκευή και λειτουργικές αναβαθμίσεις, ενώ βρίσκεται σε προχωρημένο στάδιο ολοκλήρωσης.',
    house1_scope: 'Εσωτερική & Εξωτερική Ανακαίνιση',
    house1_overview_p1: 'Αυτό το έργο αφορά την εκτεταμένη εσωτερική και εξωτερική ανακαίνιση μιας κατοικίας με θέα στη θάλασσα στις Αλυκές Χαλκίδας, η οποία βρίσκεται σε εξέλιξη (ποσοστό ολοκλήρωσης 70%). Το πεδίο περιλαμβάνει δομικές παρεμβάσεις, σκαλωσιές, επιχρίσματα και εγκατάσταση σύγχρονων ηλεκτρολογικών συστημάτων.',
    house1_overview_p2: 'Το τελικό αποτέλεσμα θα αναδεικνύει έναν εκλεπτυσμένο εσωτερικό χώρο, με ειδικά σχεδιασμένη κουζίνα, σαλόνι ενιαίας διαρρύθμισης και χρήση υλικών υψηλής ποιότητας για βέλτιστη λειτουργικότητα.',
    house1_overview_p3: 'Όλες οι εργασίες εκτελούνται υπό τη συνεχή επίβλεψη της μηχανικής και κατασκευαστικής ομάδας της OCS, διασφαλίζοντας την ποιότητα κατασκευής σε κάθε στάδιο.',
    house1_status: 'Σε Εξέλιξη (70%)',
    house1_work_1: 'Εξωτερικές δομικές εργασίες & σκαλωσιές',
    house1_work_2: 'Αναδιαμόρφωση εσωτερικής διαρρύθμισης',
    house1_work_3: 'Πλήρη επιχρίσματα (σοβάδες) & χρωματισμοί',
    house1_work_4: 'Τοποθέτηση ειδικά σχεδιασμένης κουζίνας',
    house1_work_5: 'Δάπεδα & πλακάκια',
    house1_work_6: 'Ηλεκτρολογική εγκατάσταση & φωτισμός',
    house2_title: 'Κατοικία με Θέα Θάλασσα στα Λουκίσια',
    house2_desc: 'Σύγχρονη κατοικία με θέα στη θάλασσα στα Λουκίσια, η οποία βρίσκεται σε εξέλιξη. Το έργο συνδυάζει μοντέρνο αρχιτεκτονικό σχεδιασμό, ενεργειακή αποδοτικότητα και υψηλές προδιαγραφές κατασκευής.',
    house2_scope: 'Νέα Κατασκευή Κατοικίας',
    house2_overview_p1: 'Αυτό το έργο αφορά την κατασκευή μιας νέας σύγχρονης κατοικίας στα Λουκίσια, η οποία βρίσκεται σε εξέλιξη (ποσοστό ολοκλήρωσης 65%). Το πεδίο εργασιών καλύπτει την κατασκευή του φέροντος οργανισμού, τις τοιχοποιίες, τα επιχρίσματα και τις γενικές οικοδομικές εργασίες.',
    house2_overview_p2: 'Σχεδιασμένη με σύγχρονες αρχιτεκτονικές γραμμές, η κατοικία συνδυάζει ενεργειακή αποδοτικότητα, δομική ανθεκτικότητα και υψηλές προδιαγραφές κατασκευής.',
    house2_overview_p3: 'Η ομάδα μηχανικών μας επιβλέπει ολόκληρη την κατασκευαστική διαδικασία, συντονίζοντας εξειδικευμένα συνεργεία και πραγματοποιώντας τακτικούς ελέγχους σε κάθε στάδιο.',
    house2_status: 'Σε Εξέλιξη (65%)',
    house2_work_1: 'Φέρων οργανισμός από οπλισμένο σκυρόδεμα',
    house2_work_2: 'Κατασκευή τοιχοποιίας & τούβλων',
    house2_work_3: 'Σύστημα εξωτερικής θερμομόνωσης (θερμοπρόσοψη)',
    house2_work_4: 'Ηλεκτρολογικές & υδραυλικές εγκαταστάσεις',
    house2_work_5: 'Επενδύσεις πλακιδίων & δάπεδα premium',
    house2_work_6: 'Εσωτερικοί & εξωτερικοί χρωματισμοί',
    house3_title: 'Ανακαίνιση Βίλας με Θέα Θάλασσα – Σκορπονέρια',
    house3_desc: 'Εξωτερική ανακαίνιση βίλας με θέα στη θάλασσα στα Σκορπονέρια, με κατασκευή custom infinity pool και σύγχρονες αρχιτεκτονικές παρεμβάσεις που αναβαθμίζουν τον εξωτερικό χώρο και την εμπειρία διαβίωσης.',
    house3_scope: 'Εξωτερική Ανακαίνιση & Κατασκευή Infinity Pool',
    house3_overview_p1: 'Αυτό το έργο αφορά την εξωτερική ανακαίνιση και την κατασκευή μιας custom πισίνας infinity σε μια βίλα με θέα στη θάλασσα στα Σκορπονέρια, με την πρόοδο των εργασιών να βρίσκεται στο 90%. Το πεδίο περιλαμβάνει αποκατάσταση των όψεων, εξωτερική θερμομόνωση, εκσκαφές και σκυροδέτηση της πισίνας.',
    house3_overview_p2: 'Η διαμόρφωση έχει σχεδιαστεί για να προσφέρει μια ενοποιημένη εμπειρία εσωτερικού-εξωτερικού χώρου, ενσωματώνοντας σύγχρονα συστήματα στεγανοποίησης, premium επενδύσεις και συστήματα φιλτραρίσματος.',
    house3_overview_p3: 'Όλες οι εργασίες εκτελούνται υπό τη συνεχή επίβλεψη της μηχανικής ομάδας της OCS, διασφαλίζοντας την ποιότητα κατασκευής και την τήρηση των τεχνικών προδιαγραφών.',
    house3_status: 'Σε Εξέλιξη (90%)',
    house3_work_1: 'Εκσκαφή & προετοιμασία εργοταξίου',
    house3_work_2: 'Κατασκευή φέροντος οργανισμού infinity pool',
    house3_work_3: 'Αποκατάσταση όψεων & θερμομόνωση',
    house3_work_4: 'Στεγανοποίηση & επένδυση πλακιδίων',
    house3_work_5: 'Έξυπνος φωτισμός & συστήματα φιλτραρίσματος πισίνας',
    house3_work_6: 'Διαμόρφωση deck & περιβάλλοντος χώρου',
    cookie_title: 'Πολιτική Cookies & Απορρήτου',
    cookie_updated: 'Τελευταία ενημέρωση: Ιανουάριος 2024',
    cookie_h1: '1. Εισαγωγή',
    cookie_p1: 'Η Online Construction Services (OCS) («εμείς», «εμάς» ή «μας») δεσμεύεται να προστατεύει τα προσωπικά σας δεδομένα και να σέβεται την ιδιωτικότητά σας. Αυτή η Πολιτική Cookies και Απορρήτου εξηγεί πώς συλλέγουμε, χρησιμοποιούμε και προστατεύουμε τις πληροφορίες που παρέχετε όταν επισκέπτεστε τον ιστότοπό μας.',
    cookie_h2: '2. Υπεύθυνος Επεξεργασίας Δεδομένων',
    cookie_p2: 'Ο υπεύθυνος επεξεργασίας δεδομένων που είναι υπεύθυνος για τα προσωπικά σας δεδομένα είναι η Online Construction Services (OCS).',
    cookie_contact: 'Επικοινωνία:',
    cookie_phone: 'Τηλέφωνο:',
    cookie_h3: '3. Τι Δεδομένα Συλλέγουμε',
    cookie_p3: 'Ενδέχεται να συλλέξουμε τους ακόλουθους τύπους δεδομένων:',
    cookie_li3_1: 'Στοιχεία επικοινωνίας — όνομα, διεύθυνση email και αριθμό τηλεφώνου εάν επικοινωνήσετε απευθείας μαζί μας.',
    cookie_li3_2: 'Δεδομένα χρήσης — πληροφορίες σχετικά με τον τρόπο με τον οποίο αλληλεπιδράτε με τον ιστότοπό μας (σελίδες που επισκεφτήκατε, χρόνος που αφιερώθηκε, τύπος προγράμματος περιήγησης).',
    cookie_li3_3: 'Τεχνικά δεδομένα — διεύθυνση IP, τύπος και έκδοση προγράμματος περιήγησης, ζώνη ώρας, λειτουργικό σύστημα.',
    cookie_h4: '4. Πώς Χρησιμοποιούμε τα Δεδομένα Σας',
    cookie_p4: 'Χρησιμοποιούμε τα δεδομένα που συλλέγουμε για να:',
    cookie_li4_1: 'Απαντάμε σε ερωτήματα και παρέχουμε συμβουλές για έργα.',
    cookie_li4_2: 'Βελτιώνουμε τον ιστότοπό μας και την εμπειρία χρήστη.',
    cookie_li4_3: 'Συμμορφωνόμαστε με τις νομικές υποχρεώσεις.',
    cookie_p4_sub: 'Δεν πουλάμε, ανταλλάσσουμε ή νοικιάζουμε τα προσωπικά σας δεδομένα σε τρίτους.',
    cookie_h5: '5. Cookies',
    cookie_p5: 'Ο ιστότοπός μας ενδέχεται να χρησιμοποιεί cookies — μικρά αρχεία κειμένου που τοποθετούνται στη συσκευή σας — για να βελτιώσει την εμπειρία περιήγησής σας. Τα cookies που ενδέχεται να χρησιμοποιήσουμε περιλαμβάνουν:',
    cookie_li5_1: 'Βασικά cookies — απαραίτητα για τη σωστή λειτουργία του ιστότοπου (π.χ. προτίμηση γλώσσας).',
    cookie_li5_2: 'Cookies ανάλυσης — μας βοηθούν να κατανοήσουμε πώς αλληλεπιδρούν οι επισκέπτες με τον ιστότοπο (π.χ. Google Analytics, εάν είναι ενεργοποιημένο).',
    cookie_p5_sub: 'Μπορείτε να ελέγξετε και να διαχειριστείτε τα cookies μέσω των ρυθμίσεων του προγράμματος περιήγησής σας. Σημειώστε ότι η απενεργοποίηση ορισμένων cookies ενδέχεται να επηρεάσει τη λειτουργικότητα του ιστότοπου.',
    cookie_h6: '6. Προτίμηση Γλώσσας',
    cookie_p6: 'Αυτός ο ιστότοπος αποθηκεύει την επιλεγμένη προτίμηση γλώσσας στο localStorage του προγράμματος περιήγησής σας. Αυτά τα δεδομένα δεν μεταδίδονται σε κανέναν διακομιστή και παραμένουν μόνο στη συσκευή σας.',
    cookie_h7: '7. Τα Δικαιώματά Σας (GDPR)',
    cookie_p7: 'Σύμφωνα με τον Γενικό Κανονισμό Προστασίας Δεδομένων (GDPR), έχετε το δικαίωμα να:',
    cookie_li7_1: 'Έχετε πρόσβαση στα προσωπικά δεδομένα που διατηρούμε για εσάς.',
    cookie_li7_2: 'Ζητήσετε τη διόρθωση ανακριβών δεδομένων.',
    cookie_li7_3: 'Ζητήσετε τη διαγραφή των δεδομένων σας («δικαίωμα στη λήθη»).',
    cookie_li7_4: 'Εναντιωθείτε ή να περιορίσετε τον τρόπο με τον οποίο επεξεργαζόμαστε τα δεδομένα σας.',
    cookie_li7_5: 'Φορητότητα δεδομένων — λάβετε τα δεδομένα σας σε δομημένη, αναγνώσιμη από μηχανή μορφή.',
    cookie_li7_6: 'Υποβάλετε καταγγελία σε εποπτική αρχή.',
    cookie_p7_sub: 'Για να ασκήσετε οποιοδήποτε από αυτά τα δικαιώματα, επικοινωνήστε μαζί μας στο:',
    cookie_h8: '8. Διατήρηση Δεδομένων',
    cookie_p8: 'Διατηρούμε τα προσωπικά δεδομένα μόνο για όσο διάστημα είναι απαραίτητο για τους σκοπούς που περιγράφονται σε αυτήν την πολιτική ή όπως απαιτείται από την ισχύουσα νομοθεσία.',
    cookie_h9: '9. Σύνδεσμοι Τρίτων',
    cookie_p9: 'Ο ιστότοπός μας ενδέχεται να περιέχει συνδέσμους προς ιστότοπους τρίτων. Δεν φέρουμε ευθύνη για τις πρακτικές απορρήτου ή το περιεχόμενο αυτών των ιστότοπων και σας ενθαρρύνουμε να διαβάσετε τις πολιτικές απορρήτου τους.',
    cookie_h10: '10. Αλλαγές σε Αυτήν την Πολιτική',
    cookie_p10: 'Ενδέχεται να ενημερώνουμε αυτήν την Πολιτική Cookies και Απορρήτου κατά διαστήματα. Οποιεσδήποτε αλλαγές θα δημοσιεύονται σε αυτήν τη σελίδα με ενημερωμένη ημερομηνία αναθεώρησης. Σας ενθαρρύνουμε να ελέγχετε αυτήν τη σελίδα περιοδικά.',
    cookie_h11: '11. Επικοινωνία',
    cookie_p11: 'Εάν έχετε οποιεσδήποτε ερωτήσεις σχετικά με αυτήν την πολιτική ή τον τρόπο με τον οποίο χειριζόμαστε τα δεδομένα σας, επικοινωνήστε με:',
    cookie_pm: 'Ετεοκλής Στασινόπουλος — Project Manager',
    type_villa: 'Πολυτελής Βίλα',
    type_house: 'Μονοκατοικία',
    type_residence: 'Κατοικία με Θέα Θάλασσα',

  },
  zh: {
    dir: 'ltr',
    nav_home: '首页', nav_about: '关于', nav_services: '服务',
    nav_projects: '项目', nav_realestate: '房地产', nav_contact: '联系',
    realestate_coming_soon: '即将推出',
    realestate_journey: '您准备好开启您的房地产之旅了吗？',
    realestate_tagline_1: '寻找房产',
    realestate_tagline_2: '易如反掌。',
    realestate_tagline_3: '寻得所爱',
    realestate_tagline_4: '却非易事。',
    realestate_sub_brand: 'OCS 房地产',
    hero_label: 'Online Construction Services',
    hero_h1: '以目标建造，<br>以精度交付。',
    hero_sub: '我们承接各种规模的建筑和翻新项目，以优质工艺、专业监督和对细节的关注为核心。',
    hero_cta1: '查看项目', hero_cta2: '关于我们',
    hero_scroll: '滚动',
    stats_founded: '成立年份', stats_projects: '完成项目',
    stats_team: '专业团队成员', stats_years: '行业经验年限',
    slider_label: '我们的作品',
    slider_h2: '改造前后对比',
    slider_p: '完整的外部翻新工程——从毛坯建筑到带泳池的豪华别墅。',
    slider_before: '改造前', slider_after: '改造后',
    services_label: '我们的服务',
    services_h2: '服务项目',
    services_p: '从新建工程到全面翻新，我们以经验丰富的工程师和专业团队管理每个阶段。',
    s1_title: '新建工程', s1_p: '住宅和商业建筑，从地基到最终交付。',
    s2_title: '翻新改造', s2_p: '公寓、住宅、办公室和商铺的全面室内翻新。',
    s3_title: '工程技术支持', s3_p: '许可证、设计研究、建筑图纸和项目咨询。',
    s4_title: '外立面与节能', s4_p: '保温系统、外立面修复、防水和屋顶维修。',
    s5_title: '项目监督管理', s5_p: '全程持续现场协调与质量控制。',
    learn_more: '了解更多',
    projects_label: '项目集',
    projects_h2: '项目',
    projects_p: '住宅翻新、外部修复和新建工程的精选完工作品。',
    view_all: '查看全部项目',
    cta_h2: '准备好开始您的项目了吗？',
    cta_p: '联系我们的团队进行咨询和项目报价。',
    cta_btn: '联系我们',
    footer_tagline: '高端建筑和翻新服务——以质量为基础，以精度交付。',
    footer_nav: '导航', footer_services: '服务', footer_contact_title: '联系方式',
    footer_legal: '法律',
    cookie_link: 'Cookie与隐私政策',
    footer_copy: '© 2024 Online Construction Services (OCS). 保留所有权利。',
    pm_label: '项目经理',
    about_hero_p: '成立于2024年，建立在数十年综合工程和建筑经验之上。',
    about_story_label: '我们的故事', about_who_h2: '我们是谁',
    about_p1: 'OCS成立于2024年，源于通过我们长期技术公司承接的建筑项目需求的持续增长。',
    about_p2: '凭借多年建筑和工程领域经验，成立专业建筑公司是实现更好项目协调、直接监督和更高效管理的必要步骤。',
    about_p3: '依托强大技术背景，我们与土木工程师、建筑师、测量师、机械和电气工程师及专业施工队伍紧密合作。',
    about_p4: '我们承接新住宅建筑、翻新、修复、商业项目、能源升级和完整交钥匙解决方案等各类建筑项目。',
    about_phil_label: '我们的理念',
    about_phil_h2: '"每个项目都值得专业、责任和尊重。"',
    about_phil_p: '我们的方法基于正确规划、优质工艺、细节关注以及项目每个阶段与客户的持续沟通。目标是交付兼顾功能、耐久性和高建筑标准的项目。',
    about_drives_label: '驱动我们的力量', about_approach_h2: '我们的方法',
    about_app_p1: '在OCS，我们相信每个项目都应以专业、责任和对客户愿景的尊重来对待。',
    about_app_p2: '我们的目标是交付兼顾功能性、耐久性和高建筑标准的项目，建立基于信任的长期关系。',
    about_app_p3: '从小规模翻新到大型建筑项目，我们以同等专业水平对待每项工作。',
    view_services: '查看我们的服务',
    about_team_label: '我们的团队', about_team_h2: '专家与专业人士',
    about_team_p: '我们与多学科持证专业人员和熟练工人团队合作。',
    team_civil_h4: '土木工程师', team_civil_p: '结构设计、钢筋混凝土和施工监督。',
    team_arch_h4: '建筑师', team_arch_p: '建筑图纸、许可证和空间规划解决方案。',
    team_survey_h4: '测量师', team_survey_p: '地形测量、边界测量和现场分析。',
    team_mep_h4: 'MEP工程师', team_mep_p: '机械、电气和管道系统设计与安装。',
    team_crew_h4: '施工队伍', team_crew_p: '砌体、抹灰、铺砖和精装修方面的专业工人。',
    srv_page_label: '我们的服务', srv_page_h1: '服务项目',
    srv_page_p: 'OCS承接各种规模的建筑和技术项目，以优质执行、监督和建筑质量为重点提供可靠解决方案。',
    srv1_label: '建设', srv1_p: '我们承接从初始阶段到最终交付的住宅和商业建筑建设。',
    srv1_li1: '钢筋混凝土工程', srv1_li2: '砌体和抹灰', srv1_li3: '结构建设工程',
    srv1_li4: '交钥匙住宅项目', srv1_li5: '工地监督与协调', srv1_li6: '一般建设工程',
    srv2_label: '翻新', srv2_p: '公寓、住宅、办公室、商铺和商业空间的完整翻新工程。',
    srv2_li1: '室内改造', srv2_li2: '厨房和浴室翻新', srv2_li3: '地板和瓷砖工程',
    srv2_li4: '吊顶和石膏板', srv2_li5: '粉刷工程', srv2_li6: '空间重新规划',
    srv3_label: '技术支持', srv3_p: '与工程团队合作，提供全面的技术支持和项目指导。',
    srv3_li1: '建筑许可证', srv3_li2: '工程研究', srv3_li3: '建筑图纸',
    srv3_li4: '地形测量', srv3_li5: '技术检查', srv3_li6: '项目监督与咨询',
    srv4_label: '外立面', srv4_p: '承接外部翻新和修复工程，提升建筑外观和能源性能。',
    srv4_li1: '保温系统', srv4_li2: '外立面修复与粉刷', srv4_li3: '防水工程',
    srv4_li4: '屋顶维修与隔热', srv4_li5: '阳台修复', srv4_li6: '外部维护工程',

    srv5_label: '管理', srv5_p: '通过持续监督和协调监控每个项目，确保正确执行和按时完成。',
    srv5_li1: '建筑质量控制', srv5_li2: '工地组织', srv5_li3: '协调施工队和供应商',
    srv5_li4: '符合项目规范', srv5_li5: '时间进度管理', srv5_li6: '与客户直接沟通',
    proj_page_label: '项目集', proj_page_h1: '项目',
    proj_page_p: '在OCS，每个项目都体现了我们对优质建筑、合理规划和细节关注的承诺。',
    filter_all: '全部', filter_renovation: '翻新', filter_construction: '建设', filter_exterior: '外立面', filter_interior: '室内',
    proj_more_soon: '更多项目即将推出——作品集持续更新。',
    contact_hero_p: '联系我们讨论您的项目，我们很乐意为您提供帮助。',
    contact_lets_talk: '联系我们',
    contact_sub: '我们随时解答有关建筑和翻新的任何问题。',
    contact_phone_lbl: '电话', contact_area_lbl: '地区', contact_area_val: '哈尔基斯，埃维亚',
    contact_form_title: '发送消息',
    contact_form_p: '填写表格，我们将尽快回复您。',
    contact_name_lbl: '全名 *', contact_phone_field: '电话', contact_email_lbl: '电子邮件 *',
    contact_service_lbl: '服务', contact_msg_lbl: '留言 *',
    contact_required: '* 必填项', contact_submit_btn: '发送消息',
    contact_service_placeholder: '— 选择服务 —', contact_other: '其他',
    contact_success_msg: '✓ 您的消息已成功发送！我们将很快与您联系。',
    // --- Extended translations ---
    proj_info_category: '类别',
    proj_info_type: '类型',
    proj_info_scope: '范围',
    proj_info_status: '状态',
    proj_info_year: '年份',
    proj_status_completed: '已完工',
    project_gallery_title: '项目图集',
    project_overview_title: '项目概况',
    project_about_title: '关于该项目',
    project_back_all: '返回全部项目',
    project_more_works: '更多项目',
    project_related_title: '相关作品',
    proj_rail_kick: 'OCS 项目集',
    proj_intro_p1: '在 Online Construction Services (OCS)，每一个项目都体现我们对优质建筑、合理规划和对细节关注的承诺。',
    proj_intro_p2: '我们的项目集包括住宅开发、翻新、商业项目、外墙修复和技术工程，这些都是通过我们施工和工程团队的结合经验完成的。',
    proj_intro_p3: '从小型翻新到高要求的建筑项目，我们以同样的专业水平、监督和责任感对待每一个项目。',
    proj_intro_p4: '您可以在下方找到精选项目，它们代表了我们在不同领域和项目类型中的工作和建造方法。',
    cat_interior_exterior: '室内外翻新',
    cat_residential_construction: '住宅建设',
    cat_interior_joinery: '室内设计与精细木工',
    cat_exterior_landscaping: '室外与景观美化',
    villa_title: '别墅外部翻新',
    villa_desc: '完整的外部改造——从脚手架和毛坯施工到包含泳池、景观和优质外墙工程的落成豪华别墅。',
    villa_work_1: '外墙翻新与涂装',
    villa_work_2: '泳池建造与装饰',
    villa_work_3: '玻璃护栏安装',
    villa_work_4: '室外铺装与景观美化',
    villa_work_5: '室外照明',
    villa_work_6: '百叶窗和门窗安装',
    villa_overview_p1: '该项目涉及一座双层住宅别墅的完整外部翻新，从早期施工阶段一直到最终交付。工作范围涵盖结构和外墙工程、泳池建造和装饰、室外景观美化以及完整的现场协调。',
    villa_overview_p2: '最终成果展示了显著的变化——从带有脚手架的毛坯、未完工结构转变为拥有洁白外墙、玻璃护栏泳池、室外照明和成熟景观的精致豪华别墅。',
    villa_overview_p3: '所有工程均在 OCS 工程和施工团队的持续现场监督下进行，确保项目每个阶段的质量控制。',
    house1_title: '哈尔基达阿利凯斯海景住宅翻新',
    house1_desc: '位于哈尔基达阿利凯斯的一处海景住宅正在进行全面的室内外翻新。项目融合现代设计、高品质施工与功能升级，目前已进入后期施工阶段。',
    house1_scope: '室内与室外翻新',
    house1_overview_p1: '该项目涉及位于哈尔基达阿利凯斯的一处海景住宅的全面室内外翻新，目前工程进度已达70%。工程范围包括结构改造、外部脚手架搭建、室内抹灰以及现代电气与照明系统的安装。',
    house1_overview_p2: '设计融合了现代空间布局，配备定制厨房和采用高档材料打造的开放式客厅，旨在最大化功能性与视觉美感。',
    house1_overview_p3: '所有工程均在 OCS 工程和施工团队的现场监督下进行，确保从拆除到最终交付的每一步都符合高标准。',
    house1_status: '建设中 (70%)',
    house1_work_1: '外部结构工程与脚手架',
    house1_work_2: '室内布局重新规划',
    house1_work_3: '完整抹灰与粉刷',
    house1_work_4: '定制厨房安装',
    house1_work_5: '地板与瓷砖铺设',
    house1_work_6: '电气与照明系统安装',
    house2_title: '卢基西亚海景住宅',
    house2_desc: '位于希腊卢基西亚的一座现代海景住宅，目前正在建设中。项目融合现代建筑设计、节能理念以及高品质施工标准。',
    house2_scope: '新建住宅',
    house2_overview_p1: '该项目涉及在希腊卢基西亚新建一座现代住宅，目前已完工65%。工作范围涵盖主体结构施工、砌砖、抹灰以及一般建筑安装工程。',
    house2_overview_p2: '房屋设计采用现代建筑线条，融合了节能解决方案、结构耐久性以及高品质施工标准。',
    house2_overview_p3: '我们的工程团队全程监督施工过程，协调专业施工队伍并在每个阶段进行质量检查。',
    house2_status: '建设中 (65%)',
    house2_work_1: '钢筋混凝土结构框架',
    house2_work_2: '砌体与砖墙施工',
    house2_work_3: '外墙外保温系统',
    house2_work_4: '电气与管道系统安装',
    house2_work_5: '优质瓷砖与地板铺设',
    house2_work_6: '室内与室外粉刷',
    house3_title: '斯科尔波内里亚海景别墅翻新',
    house3_desc: '位于斯科尔波内里亚的一栋海景别墅正在进行外部翻新，并配备定制 Infinity Pool。项目融合现代设计、高品质施工以及卓越的户外生活体验。',
    house3_scope: '外部翻新与 Infinity Pool 建造',
    house3_overview_p1: '该项目涉及斯科尔波内里亚一栋海景别墅的全面外部翻新与定制无边泳池建造，目前工程进度已达90%。工作范围包括外立面修复、高端隔热工程、泳池结构开挖和混凝土浇筑。',
    house3_overview_p2: '空间布局经过优化，致力于实现室内外空间的无缝结合，配备了高品质饰面瓷砖、现代防水系统、玻璃护栏以及智能泳池过滤系统。',
    house3_overview_p3: '所有结构和精装工程均在 OCS 工程和施工团队的持续现场监督下进行，确保完全符合建筑规范并呈现卓越的视觉效果。',
    house3_status: '建设中 (90%)',
    house3_work_1: '开挖与场地准备',
    house3_work_2: 'Infinity Pool 结构框架',
    house3_work_3: '外墙修复与保温',
    house3_work_4: '防水与瓷砖铺贴',
    house3_work_5: '智能照明与泳池过滤系统',
    house3_work_6: '平台铺设与户外景观',
    cookie_title: 'Cookie 与隐私政策',
    cookie_updated: '最后更新：2024年1月',
    cookie_h1: '1. 简介',
    cookie_p1: 'Online Construction Services (OCS)（简称“我们”或“我们的”）致力于保护您的个人数据并尊重您的隐私。本 Cookie 和隐私政策解释了当您访问我们的网站时，我们如何收集、使用和保护您提供的任何信息。',
    cookie_h2: '2. 数据控制者',
    cookie_p2: '负责您个人数据的数据控制者为 Online Construction Services (OCS)。',
    cookie_contact: '联系方式：',
    cookie_phone: '电话：',
    cookie_h3: '3. 我们收集哪些数据',
    cookie_p3: '我们可能会收集以下类型的数据：',
    cookie_li3_1: '联系信息 — 如果您直接联系我们，包括姓名、电子邮件地址和电话号码。',
    cookie_li3_2: '使用数据 — 关于您如何与网站互动的信息（访问的页面、花费的时间、浏览器类型）。',
    cookie_li3_3: '技术数据 — IP 地址、浏览器类型和版本、时区、操作系统。',
    cookie_h4: '4. 我们如何使用您的数据',
    cookie_p4: '我们使用收集的数据来：',
    cookie_li4_1: '回复咨询并提供项目咨询。',
    cookie_li4_2: '改进我们的网站和用户体验。',
    cookie_li4_3: '遵守法律义务。',
    cookie_p4_sub: '我们不会将您的个人数据出售、交易或出租给第三方。',
    cookie_h5: '5. Cookie',
    cookie_p5: '我们的网站可能会使用 Cookie（放置在您设备上的小文本文件）来改善您的浏览体验。我们可能使用的 Cookie 包括：',
    cookie_li5_1: '必要 Cookie — 网站正常运行所必需的（例如语言偏好）。',
    cookie_li5_2: '分析 Cookie — 帮助我们了解访问者如何与网站互动（例如，如果启用，Google Analytics）。',
    cookie_p5_sub: '您可以通过浏览器设置控制和管理 Cookie。请注意，禁用某些 Cookie 可能会影响网站的功能。',
    cookie_h6: '6. 语言偏好',
    cookie_p6: '本网站将您选择的语言偏好存储在浏览器的 localStorage 中。此数据不会传输到任何服务器，仅保留在您的设备上。',
    cookie_h7: '7. 您的权利（GDPR）',
    cookie_p7: '根据《通用数据保护条例》（GDPR），您有权：',
    cookie_li7_1: '访问我们持有的关于您的个人数据。',
    cookie_li7_2: '要求纠正不准确的数据。',
    cookie_li7_3: '要求删除您的数据（“被遗忘权”）。',
    cookie_li7_4: '反对或限制我们处理您数据的方式。',
    cookie_li7_5: '数据可移植性 — 以结构化、机器可读的格式接收您的数据。',
    cookie_li7_6: '向监管机构投诉。',
    cookie_p7_sub: '如欲行使任何上述权利，请通过以下方式与我们联系：',
    cookie_h8: '8. 数据保留',
    cookie_p8: '我们仅在为本政策所述目的所必需的期限内，或适用法律要求的期限内保留个人数据。',
    cookie_h9: '9. 第三方链接',
    cookie_p9: '我们的网站可能包含指向第三方网站的链接。我们对此类网站的隐私做法或内容不承担任何责任，并鼓励您阅读其隐私政策。',
    cookie_h10: '10. 本政策的变更',
    cookie_p10: '我们可能会不时更新本 Cookie 和隐私政策。任何变更都将在此页面上公布，并更新修订日期。我们鼓励您定期查看此页面。',
    cookie_h11: '11. 联系',
    cookie_p11: '如果您对本政策或我们如何处理您的数据有任何疑问，请联系：',
    cookie_pm: 'Eteoklis Stasinopoulos — 项目经理',
    type_villa: '别墅住宅',
    type_house: '住宅房屋',
    type_residence: '海景住宅',

  },
  he: {
    dir: 'rtl',
    nav_home: 'בית', nav_about: 'אודות', nav_services: 'שירותים',
    nav_projects: 'פרויקטים', nav_realestate: 'נדל"ן', nav_contact: 'צור קשר',
    realestate_coming_soon: 'בקרוב',
    realestate_journey: 'האם אתם מוכנים למסע שלכם בנדל"ן?',
    realestate_tagline_1: 'למצוא נכס',
    realestate_tagline_2: 'זה קל.',
    realestate_tagline_3: 'למצוא את הנכס הנכון',
    realestate_tagline_4: 'זה לא.',
    realestate_sub_brand: 'OCS נדל"ן',
    hero_label: 'Online Construction Services',
    hero_h1: 'בונים עם מטרה,<br>מסיימים בדיוק.',
    hero_sub: 'אנו מקבלים על עצמנו פרויקטי בנייה ושיפוץ בכל היקף — עם עבודה איכותית, פיקוח נאות ותשומת לב לפרטים.',
    hero_cta1: 'צפה בפרויקטים', hero_cta2: 'אודותינו',
    hero_scroll: 'גלול',
    stats_founded: 'נוסדה', stats_projects: 'פרויקטים שהושלמו',
    stats_team: 'מומחים בצוות', stats_years: 'שנות ניסיון',
    slider_label: 'העבודה שלנו',
    slider_h2: 'לפני ואחרי',
    slider_p: 'שיפוץ חיצוני מלא — מבנייה גולמית לווילה יוקרתית עם בריכה.',
    slider_before: 'לפני', slider_after: 'אחרי',
    services_label: 'מה אנחנו עושים',
    services_h2: 'השירותים שלנו',
    services_p: 'מבנייה חדשה ועד שיפוץ מלא — אנו מנהלים כל שלב עם מהנדסים מנוסים.',
    s1_title: 'בנייה חדשה', s1_p: 'בניינים למגורים ומסחר מהיסוד ועד המסירה הסופית.',
    s2_title: 'שיפוצים', s2_p: 'שיפוץ פנים מלא לדירות, בתים, משרדים וחנויות.',
    s3_title: 'תמיכה הנדסית וטכנית', s3_p: 'היתרים, תוכניות, שרטוטים אדריכליים וייעוץ מקצועי.',
    s4_title: 'עבודות חוץ ואנרגיה', s4_p: 'בידוד חום, חיפוי חזיתות, איטום וחיפויי גגות.',
    s5_title: 'פיקוח וניהול פרויקטים', s5_p: 'פיקוח רציף ובקרת איכות לאורך כל שלבי הפרויקט.',
    learn_more: 'קרא עוד',
    projects_label: 'תיק עבודות',
    projects_h2: 'פרויקטים',
    projects_p: 'מבחר עבודות שהושלמו בשיפוצי מגורים, שיקום חזיתות ובנייה חדשה.',
    view_all: 'כל הפרויקטים',
    cta_h2: 'מוכנים להתחיל את הפרויקט שלכם?',
    cta_p: 'צרו קשר עם הצוות שלנו לייעוץ ואומדן עלויות.',
    cta_btn: 'צור קשר',
    footer_tagline: 'שירותי בנייה ושיפוץ ברמה גבוהה — מבוססים על איכות ומסורת.',
    footer_nav: 'ניווט', footer_services: 'שירותים', footer_contact_title: 'צור קשר',
    footer_legal: 'משפטי',
    cookie_link: 'מדיניות עוגיות ופרטיות',
    footer_copy: '© 2024 Online Construction Services (OCS). כל הזכויות שמורות.',
    pm_label: 'מנהל פרויקט',
    about_hero_p: 'נוסדה ב-2024. בנויה על עשרות שנים של ניסיון משולב בהנדסה ובנייה.',
    about_story_label: 'הסיפור שלנו', about_who_h2: 'מי אנחנו',
    about_p1: 'OCS נוסדה ב-2024 בעקבות הביקוש הגובר לפרויקטי בנייה שהתבצעו דרך חברת הטכנולוגיה הוותיקה שלנו.',
    about_p2: 'עם שנות ניסיון בתחום הבנייה וההנדסה, הקמת חברת בנייה ייעודית הייתה צעד הכרחי לשיפור תיאום הפרויקטים ופיקוח ישיר.',
    about_p3: 'מתוך רקע טכני חזק, אנו עובדים עם מהנדסים אזרחיים, אדריכלים, מודדים, מהנדסי מכונות וחשמל וצוותי בנייה מיוחדים.',
    about_p4: 'אנו מקבלים פרויקטים של בניינים למגורים, שיפוצים, שיקומים, פרויקטים מסחריים, שדרוגי אנרגיה ופתרונות מפתח בידיים.',
    about_phil_label: 'הפילוסופיה שלנו',
    about_phil_h2: '"כל פרויקט ראוי למקצועיות, אחריות וכבוד."',
    about_phil_p: 'הגישה שלנו מבוססת על תכנון נכון, עבודה איכותית, תשומת לב לפרטים ותקשורת רציפה עם הלקוח לאורך כל שלבי הפרויקט.',
    about_drives_label: 'מה מניע אותנו', about_approach_h2: 'הגישה שלנו',
    about_app_p1: 'ב-OCS, אנו מאמינים שכל פרויקט צריך להיות מטופל במקצועיות, אחריות וכבוד לחזון הלקוח.',
    about_app_p2: 'המטרה שלנו היא לספק פרויקטים המשלבים פונקציונליות, עמידות ותקני בנייה גבוהים.',
    about_app_p3: 'מאנוויות קטנות ועד פרויקטי בנייה מאתגרים, אנו מתייחסים לכל עבודה באותה מקצועיות ואחריות.',
    view_services: 'צפה בשירותים שלנו',
    about_team_label: 'הצוות שלנו', about_team_h2: 'מומחים ואנשי מקצוע',
    about_team_p: 'אנו משתפים פעולה עם צוות רב-תחומי של אנשי מקצוע מורשים ופועלים מיומנים.',
    team_civil_h4: 'מהנדסים אזרחיים', team_civil_p: 'תכנון קונסטרוקציה, בטון מזוין ופיקוח על הבנייה.',
    team_arch_h4: 'אדריכלים', team_arch_p: 'שרטוטים אדריכליים, היתרים ופתרונות תכנון חלל.',
    team_survey_h4: 'מודדים', team_survey_p: 'סקרים טופוגרפיים, מדידות גבולות וניתוח אתר.',
    team_mep_h4: 'מהנדסי MEP', team_mep_p: 'תכנון והתקנה של מערכות מכניות, חשמליות ואינסטלציה.',
    team_crew_h4: 'צוותי בנייה', team_crew_p: 'בעלי מקצוע מיוחדים בבנייה, טיח, ריצוף וגימור.',
    srv_page_label: 'מה אנחנו עושים', srv_page_h1: 'שירותים',
    srv_page_p: 'OCS מקבלת פרויקטי בנייה וטכניים בכל היקף, ומספקת פתרונות אמינים עם דגש על ביצוע נכון, פיקוח ואיכות בנייה.',
    srv1_label: 'בנייה', srv1_p: 'אנו מקבלים על עצמנו בנייה של מבני מגורים ומסחר, מהשלב הראשוני ועד המסירה הסופית.',
    srv1_li1: 'עבודות בטון מזוין', srv1_li2: 'בנייה וטיח', srv1_li3: 'עבודות קונסטרוקציה',
    srv1_li4: 'פרויקטים מפתח בידיים', srv1_li5: 'פיקוח וקואורדינציה באתר', srv1_li6: 'עבודות בנייה כלליות',
    srv2_label: 'שיפוצים', srv2_p: 'עבודות שיפוץ מלאות לדירות, בתים, משרדים, חנויות ומרחבים מסחריים.',
    srv2_li1: 'שיפוץ פנים', srv2_li2: 'שיפוץ מטבח ואמבטיה', srv2_li3: 'עבודות ריצוף ואריחים',
    srv2_li4: 'תקרות וגבס', srv2_li5: 'עבודות צביעה', srv2_li6: 'שינוי תצורת חלל',
    srv3_label: 'תמיכה טכנית', srv3_p: 'בשיתוף פעולה עם צוות המהנדסים שלנו, אנו מספקים תמיכה טכנית מלאה והכוונת פרויקטים.',
    srv3_li1: 'היתרי בנייה', srv3_li2: 'מחקרי הנדסה', srv3_li3: 'שרטוטים אדריכליים',
    srv3_li4: 'סקרים טופוגרפיים', srv3_li5: 'בדיקות טכניות', srv3_li6: 'פיקוח וייעוץ פרויקטים',
    srv4_label: 'חוץ', srv4_p: 'אנו מקבלים עבודות שיפוץ חיצוני ושיקום לשיפור המראה והביצועים האנרגטיים של המבנה.',
    srv4_li1: 'מערכות בידוד חום', srv4_li2: 'תיקון ולכה לחזית', srv4_li3: 'עבודות איטום',
    srv4_li4: 'תיקון גג ובידוד', srv4_li5: 'שיקום מרפסות', srv4_li6: 'תחזוקת חוץ',
    srv5_label: 'ניהול', srv5_p: 'כל פרויקט מנוהל עם פיקוח וקואורדינציה רציפים להבטחת ביצוע נכון והשלמה בזמן.',
    srv5_li1: 'בקרת איכות בנייה', srv5_li2: 'ארגון האתר', srv5_li3: 'תיאום צוותים וספקים',
    srv5_li4: 'עמידה במפרטי הפרויקט', srv5_li5: 'ניהול לוח זמנים', srv5_li6: 'תקשורת ישירה עם הלקוח',
    proj_page_label: 'תיק עבודות', proj_page_h1: 'פרויקטים',
    proj_page_p: 'ב-OCS, כל פרויקט משקף את מחויבותנו לבנייה איכותית, תכנון נכון ותשומת לב לפרטים.',
    filter_all: 'הכל', filter_renovation: 'שיפוץ', filter_construction: 'בנייה', filter_exterior: 'חוץ', filter_interior: 'פנים',
    proj_more_soon: 'פרויקטים נוספים בקרוב — תיק העבודות מתעדכן כל הזמן.',
    contact_hero_p: 'צרו קשר לדיון בפרויקט שלכם. נשמח לעזור.',
    contact_lets_talk: 'בואו נדבר',
    contact_sub: 'אנו זמינים לכל שאלה בנושא בנייה ושיפוצים.',
    contact_phone_lbl: 'טלפון', contact_area_lbl: 'אזור', contact_area_val: 'חלקידה, אוויאה',
    contact_form_title: 'שלחו לנו הודעה',
    contact_form_p: 'מלאו את הטופס ונחזור אליכם בהקדם האפשרי.',
    contact_name_lbl: 'שם מלא *', contact_phone_field: 'טלפון', contact_email_lbl: 'אימייל *',
    contact_service_lbl: 'שירות', contact_msg_lbl: 'הודעה *',
    contact_required: '* שדות חובה', contact_submit_btn: 'שליחת הודעה',
    contact_service_placeholder: '— בחר שירות —', contact_other: 'אחר',
    contact_success_msg: '✓ הודעתך נשלחה בהצלחה! ניצור אתך קשר בקרוב.',
    // --- Extended translations ---
    proj_info_category: 'קטגוריה',
    proj_info_type: 'סוג',
    proj_info_scope: 'היקף העבודה',
    proj_info_status: 'סטטוס',
    proj_info_year: 'שנה',
    proj_status_completed: 'הושלם',
    project_gallery_title: 'גלריית הפרויקט',
    project_overview_title: 'סקירת הפרויקט',
    project_about_title: 'על הפרויקט',
    project_back_all: 'בחזרה לכל הפרויקטים',
    project_more_works: 'פרויקטים נוספים',
    project_related_title: 'עבודות קשורות',
    proj_rail_kick: 'תיק עבודות OCS',
    proj_intro_p1: 'בחברת Online Construction Services (OCS), כל פרויקט משקף את מחויבותנו לבנייה איכותית, תכנון נכון ותשומת לב לפרטים.',
    proj_intro_p2: 'תיק העבודות שלנו כולל פרויקטי מגורים, שיפוצים, פרויקטים מסחריים, שיקום חזיתות ועבודות טכניות שהושלמו הודות לניסיון המשולב של צוותי הבנייה וההנדסה שלנו.',
    proj_intro_p3: 'משיפוצים קטנים ועד פרויקטי בנייה תובעניים, אנו ניגשים לכל פרויקט עם אותה רמה של מקצועיות, פיקוח ואחריות.',
    proj_intro_p4: 'להלן תוכל למצוא מבחר פרויקטים המייצגים את עבודתנו ואת גישת הבנייה שלנו במגוון תחומים וסוגי פרויקטים.',
    cat_interior_exterior: 'שיפוץ פנים וחוץ',
    cat_residential_construction: 'בנייה למגורים',
    cat_interior_joinery: 'עיצוב פנים ונגרות',
    cat_exterior_landscaping: 'עבודות חוץ ופיתוח סביבתי',
    villa_title: 'שיפוץ וילה עם נוף לים – פארוס, אבלידה',
    villa_desc: 'שיפוץ חיצוני מלא של וילה עם נוף לים בפארוס, אבלידה. הפרויקט כלל חידוש חזיתות המבנה, עבודות גמר חיצוניות ברמה גבוהה ובניית בריכת שחייה מודרנית, ליצירת סביבת מגורים יוקרתית ונעימה.',
    villa_scope: 'שיפוץ חיצוני ובניית בריכה',
    villa_work_1: 'שיפוץ וצביעת חזית',
    villa_work_2: 'בנייה וגימור של בריכה',
    villa_work_3: 'התקנת גדר זכוכית',
    villa_work_4: 'ריצוף חוץ ופיתוח שטח',
    villa_work_5: 'תאורת חוץ',
    villa_work_6: 'התקנת תריסים וחלונות',
    villa_overview_p1: 'פרויקט זה כלל שיפוץ חיצוני מלא של וילת מגורים דו-קומתית עם נוף לים בפארוס, אבלידה. היקף העבודה כיסה שיקום חזיתות ושלד, גימורים חיצוניים ברמה גבוהה, בניית בריכת שחייה מודרנית ופיתוח סביבתי.',
    villa_overview_p2: 'התוצאה הסופית מציגה מהפך אדריכלי מרשים — הכולל חזיתות מודרניות ונקיות, בריכה בגימור יוקרתי, וחללי חוץ מעוצבים לנוחות מרבית.',
    villa_overview_p3: 'כל העבודות בוצעו בפיקוח מלא של צוות ההנדסה של OCS, תוך הבטחת עמידה בלוחות הזמנים ובסטנדרטים הגבוהים ביותר של איכות ובנייה.',
    house1_title: 'שיפוץ בית 1',
    house1_desc: 'מהפך מלא של בית 1 — מפיגומים ועבודות שלד בשלב מוקדם לחלל פנימי יוקרתי גמור לחלוטיံ הכולל אזורי מגורים ומטבח בהתאמה אישית.',
    house1_scope: 'שיפוץ מלא של הנכס',
    house1_overview_p1: 'פרויקט זה כלל שיפוץ פנים וחוץ מקיף של נכס מגורים. היקף העבודה כלל התאמות מבניות, פיגומים חיצוניים נרחבים, עבודות טיח פנים מלאות והתקנת מערכות חשמל ותאורה מודרניות.',
    house1_overview_p2: 'התוצאה הסופית מציגה חלל פנימי יוקרתי ומתוחכם, הכולל מטבח בעיצוב אישי עם מכשירי חשמל מתקדמים, וסלון פתוח ומרהיב בגימור מחומרים איכותיים.',
    house1_overview_p3: 'כל העבודות בוצעו תחת פיקוח רציף באתר של צוות ההנדסה והבנייה של OCS, תוך הבטחת ביצוע ללא דופי משלב ההריסה ועד למסירה הסופית.',
    house1_work_1: 'עבודות שלד חיצוניות ופיגומים',
    house1_work_2: 'תכנון מחדש של חלוקת הפנים',
    house1_work_3: 'עבודות טיח וצבע מלאות',
    house1_work_4: 'התקנת מטבח בהתאמה אישית',
    house1_work_5: 'ריצוף וחיפוי אריחים',
    house1_work_6: 'התקנת מערכות חשמל ותאורה',
    house2_title: 'בית מגורים עם נוף לים בלוקיסיה',
    house2_desc: 'בית מגורים מודרני עם נוף לים בלוקיסיה, הנמצא כעת בשלבי בנייה. הפרויקט משלב אדריכלות מודרנית, יעילות אנרגטית וסטנדרטים גבוהים של בנייה.',
    house2_scope: 'בניית בית מגורים חדש',
    house2_overview_p1: 'פרויקט זה כולל בנייה של בית מגורים מודרני חדש בלוקיסיה, הנמצא כעת בשלבי בנייה (עם 65% השלמה). היקף העבודה מכסה את בניית השלד, עבודות לבנים, טיח ועבודות גמר כלליות.',
    house2_overview_p2: 'הבית, שעוצב בקווים אדריכליים מודרניים, משלב פתרונות חסכוניים באנרגיה, עמידות מבנית וסטנדרטים גבוהים של בנייה.',
    house2_overview_p3: 'צוות ההנדסה שלנו מפקח על תהליך הבנייה כולו, מתאם צוותים מקצועיים ומבצע בדיקות איכות בכל שלב.',
    house2_status: 'בבנייה (65%)',
    house2_work_1: 'שלד מבנה מבטון מזוין',
    house2_work_2: 'עבודות לבנים ובנייה',
    house2_work_3: 'מערכת בידוד תרמי חיצונית',
    house2_work_4: 'התקנות חשמל ואינסטלציה',
    house2_work_5: 'ריצוף וחיפוי אריחים יוקרתי',
    house2_work_6: 'צביעת פנים וחוץ',
    house3_title: 'שיפוץ וילה עם נוף לים – סקורפונריה',
    house3_desc: 'שיפוץ חיצוני של וילה עם נוף לים בסקורפונריה, הכולל בניית Infinity Pool בהתאמה אישית ועבודות גמר מודרניות היוצרות סביבת מגורים יוקרתית.',
    house3_scope: 'שיפוץ חיצוני ובניית Infinity Pool',
    house3_overview_p1: 'פרויקט זה כולל שיפוץ חיצוני מקיף ובניית בריכת אינפיניטי (Infinity Pool) בהתאמה אישית עבור וילה עם נוף לים בסקורפונריה, הנמצא כעת בשלבי סיום (90% השלמה). היקף העבודה כולל חידוש חזיתות, בידוד תרמי מתקדם, חפירה ויציקת בטון לבריכה.',
    house3_overview_p2: 'התכנון מותאם לזרימה רציפה בין אזורי הפנים והחוץ, ומשלב מערכות איטום מודרניות, חיפויי אריחים יוקרתיים, מחיצות זכוכית ומערכות סינון חכמות לבריכה.',
    house3_overview_p3: 'כל עבודות השלד והגמר מבוצעות תחת פיקוח הדוק של צוות ההנדסה של OCS, תוך הבטחת עמידה בתקני הבנייה המחמירים ביותר ורמת גימור ללא פשרות.',
    house3_status: 'בבנייה (90%)',
    house3_work_1: 'חפירה והכנת השטח',
    house3_work_2: 'שלד בריכת אינפיניטי',
    house3_work_3: 'שיקום חזית ובידוד',
    house3_work_4: 'איטום וריצוף אריחים',
    house3_work_5: 'תאורה חכמה ומערכות סינון',
    house3_work_6: 'ריצוף דק ופיתוח סביבתי',
    cookie_title: 'מדיניות עוגיות ופרטיות',
    cookie_updated: 'עודכן לאחרונה: ינואר 2024',
    cookie_h1: '1. מבוא',
    cookie_p1: 'חברת Online Construction Services (OCS) ("אנחנו", "שלנו", או "אותנו") מחויבת להגן על הנתונים האישיים שלך ולכבד את פרטיותך. מדיניות עוגיות ופרטיות זו מסבירה כיצד אנו אוספים, משתמשים ומגנים על כל מידע שאתה מספק בעת הביקור באתר האינטרנט שלנו.',
    cookie_h2: '2. מנהל מאגר המידע',
    cookie_p2: 'מנהל מאגר המידע האחראי על הנתונים האישיים שלך הוא Online Construction Services (OCS).',
    cookie_contact: 'צור קשר:',
    cookie_phone: 'טלפון:',
    cookie_h3: '3. אילו נתונים אנו אוספים',
    cookie_p3: 'אנו עשויים לאסוף את סוגי הנתונים הבאים:',
    cookie_li3_1: 'פרטי קשר — שם, כתובת אימייל ומספר טלפון אם תפנה אלינו ישירות.',
    cookie_li3_2: 'נתוני שימוש — מידע על האופן שבו אתה מקיים אינטראקציה עם האתר שלנו (דפים שבהם ביקרת, זמן שהייה, סוג הדפדפן).',
    cookie_li3_3: 'נתונים טכניים — כתובת IP, סוג וגרסת הדפדפן, אזור זמן, מערכת הפעלה.',
    cookie_h4: '4. כיצד אנו משתמשים בנתונים שלך',
    cookie_p4: 'אנו משתמשים בנתונים שאנו אוספים כדי:',
    cookie_li4_1: 'להשיב לפניות ולספק ייעוץ לפרויקט.',
    cookie_li4_2: 'לשפר את האתר ואת חוויית המשתמש שלנו.',
    cookie_li4_3: 'לעמוד בהתחייבויות משפטיות.',
    cookie_p4_sub: 'איננו מוכרים, סוחרים או משכירים את הנתונים האישיים שלך לצדדים שלישיים.',
    cookie_h5: '5. עוגיות (Cookies)',
    cookie_p5: 'האתר שלנו עשוי להשתמש בעוגיות — קבצי טקסט קטנים המוצבים במכשיר שלך — כדי לשפר את חווית הגלישה שלך. העוגיות שאנו עשויים להשתמש בהן כוללות:',
    cookie_li5_1: 'עוגיות חיוניות — נחוצות לתפקוד תקין של האתר (למשל העדפת שפה).',
    cookie_li5_2: 'עוגיות ניתוח — עוזרות לנו להבין כיצד המבקרים מקיימים אינטראקציה עם האתר (למשל גוגל אנליטיקס, אם מופעל).',
    cookie_p5_sub: 'באפשרותך לשלוט ולנהל עוגיות באמצעות הגדרות הדפדפן שלך. שים לב שנטרול עוגיות מסוימות עשוי להשפיע על תפקוד האתר.',
    cookie_h6: '6. העדפת שפה',
    cookie_p6: 'אתר זה מאחסן את העדפת השפה שבחרת ב-localStorage של הדפדפן שלך. נתונים אלו אינם מועברים לשום שרת ונשארים רק במכשיר שלך.',
    cookie_h7: '7. הזכויות שלך (GDPR)',
    cookie_p7: 'על פי תקנת הגנת הנתונים הכללית (GDPR), עומדת לך הזכות:',
    cookie_li7_1: 'לגשת לנתונים האישיים שאנו מחזיקים אודותיך.',
    cookie_li7_2: 'לבקש תיקון של נתונים לא מדויקים.',
    cookie_li7_3: 'לבקש את מחיקת הנתונים שלך ("הזכות להישכח").',
    cookie_li7_4: 'להתנגד או להגביל את האופן שבו אנו מעבדים את הנתונים שלך.',
    cookie_li7_5: 'ניידות נתונים — לקבל את הנתונים שלך בפורמט מובנה וקריא במכונה.',
    cookie_li7_6: 'להגיש תלונה לרשות פיקוח.',
    cookie_p7_sub: 'כדי לממש זכויות אלו, אנא פנה אלינו בכתובת:',
    cookie_h8: '8. שמירת נתונים',
    cookie_p8: 'אנו שומרים נתונים אישיים רק כל עוד הדבר נחוץ למטרות המפורטות במדיניות זו, או כנדרש על פי הדין החל.',
    cookie_h9: '9. קישורים לצדדים שלישיים',
    cookie_p9: 'האתר שלנו עשוי להכיל קישורים לאתרי אינטרנט של צדדים שלישיים. איננו אחראים לנוהלי הפרטיות או לתוכן של אתרים אלה וממליצים לך לעיין במדיניות הפרטיות שלהם.',
    cookie_h10: '10. שינויים במדיניות זו',
    cookie_p10: 'אנו עשויים לעדכן מדיניות עוגיות ופרטיות זו מעת לעת. כל שינוי יפורסם בדף זה עם תאריך עדכון מעודכן. אנו ממליצים לך לעיין בדף זה מעת לעת.',
    cookie_h11: '11. יצירת קשר',
    cookie_p11: 'אם יש לך שאלות כלשהן לגבי מדיניות זו או לגבי האופן שבו אנו מטפלים בנתונים שלך, אנא פנה אל:',
    cookie_pm: 'אטאוקליס סטסינופולוס — מנהל פרויקט',
    type_villa: 'וילת מגורים',
    type_house: 'בית מגורים',
    type_residence: 'בית מגורים עם נוף לים',

  }
};

/* ─── State ───────────────────────────────── */
let currentLang = localStorage.getItem('ocs-lang') || 'en';

/* ─── Apply language ──────────────────────── */
function applyLang(lang) {
  const t = TRANSLATIONS[lang];
  if (!t) return;
  currentLang = lang;
  localStorage.setItem('ocs-lang', lang);

  // Direction
  document.documentElement.setAttribute('lang', lang);
  document.documentElement.setAttribute('dir', t.dir);

  // Translate all [data-i18n] elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });

  // Active lang button
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
}

/* ─── Navbar scroll ───────────────────────── */
function initNavbar() {
  const navbar = document.getElementById('navbar');
  if (!navbar) return;
  const onScroll = () => {
    navbar.classList.toggle('scrolled', window.scrollY > 40);
  };
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  // Active link highlight
  const links = navbar.querySelectorAll('.nav-links a, .nav-mobile a');
  const page = location.pathname.split('/').pop() || 'index.html';
  links.forEach(a => {
    const href = a.getAttribute('href');
    if (href === page || (page === '' && href === 'index.html')) {
      a.classList.add('active');
    }
  });
}

/* ─── Mobile menu ─────────────────────────── */
function initHamburger() {
  const btn = document.getElementById('hamburger');
  const mobile = document.getElementById('nav-mobile');
  if (!btn || !mobile) return;
  btn.addEventListener('click', () => {
    btn.classList.toggle('open');
    mobile.classList.toggle('open');
    document.body.style.overflow = mobile.classList.contains('open') ? 'hidden' : '';
  });
  mobile.querySelectorAll('a').forEach(a => {
    a.addEventListener('click', () => {
      btn.classList.remove('open');
      mobile.classList.remove('open');
      document.body.style.overflow = '';
    });
  });
}

/* ─── Language buttons ────────────────────── */
function initLangSwitcher() {
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => applyLang(btn.getAttribute('data-lang')));
  });
}

/* ─── Scroll animations ───────────────────── */
function initAnimations() {
  const els = document.querySelectorAll('.fade-up, .fade-in');
  if (!els.length) return;
  const obs = new IntersectionObserver((entries) => {
    entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); obs.unobserve(e.target); } });
  }, { threshold: 0.12 });
  els.forEach(el => obs.observe(el));
}

/* ─── Infinite Project Rail for Mobile ───── */
function initProjectsRailLoop() {
  const rail = document.querySelector('.projects-rail');
  const track = document.querySelector('.projects-track');
  if (!rail || !track) return;

  let isMobile = window.innerWidth <= 700;
  let loopWidth = track.scrollWidth / 2;

  const resetScrollPosition = () => {
    if (isMobile && loopWidth > 0) {
      rail.scrollLeft = loopWidth;
    }
  };

  window.addEventListener('load', () => {
    loopWidth = track.scrollWidth / 2;
    resetScrollPosition();
  });

  setTimeout(() => {
    loopWidth = track.scrollWidth / 2;
    resetScrollPosition();
  }, 400);

  let isAdjusting = false;
  rail.addEventListener('scroll', () => {
    if (!isMobile || isAdjusting) return;

    loopWidth = track.scrollWidth / 2;
    if (loopWidth <= 0) return;

    const currentScroll = rail.scrollLeft;

    if (currentScroll <= 10) {
      isAdjusting = true;
      rail.scrollLeft = currentScroll + loopWidth;
      isAdjusting = false;
    } else if (currentScroll >= (loopWidth * 2) - rail.clientWidth - 10) {
      isAdjusting = true;
      rail.scrollLeft = currentScroll - loopWidth;
      isAdjusting = false;
    }
  }, { passive: true });

  window.addEventListener('resize', () => {
    const wasMobile = isMobile;
    isMobile = window.innerWidth <= 700;
    loopWidth = track.scrollWidth / 2;
    if (isMobile && !wasMobile) {
      resetScrollPosition();
    }
  });
}

/* ─── Boot ────────────────────────────────── */
document.addEventListener('DOMContentLoaded', () => {
  initNavbar();
  initHamburger();
  initLangSwitcher();
  initAnimations();
  initProjectsRailLoop();
  applyLang(currentLang);
});


